Blog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;
using System.Text;
using System.Data.Entity;
using PagedList;
using System.ServiceModel.Syndication;
using System.Web.Services;
using Blog.ViewModel;
using Blog.Common;
using System.IO;

namespace Blog.Controllers
{
    public class PostsController : Controller
    {
        BlogContext context = new BlogContext();
        PostViewModel postModel = new PostViewModel();

        private const int postsPerFeed = 25;

        public ActionResult Index(string tagName, int? page , string postSearch)
        {
            //list posts by tags 
            if (!string.IsNullOrEmpty(tagName))
            {
                postModel.Posts = GetTagPostsByTagName(tagName, page);
                postModel.TagName = tagName;

                return View(postModel);
            }

            int currentPage = page ?? 1;
            
            //search
            if(!string.IsNullOrWhiteSpace(postSearch))
            {
                postModel.Posts = context.Posts
                    .Include(p => p.Tags)
                    .Where(p => p.Title.StartsWith(postSearch))
                    .OrderBy(p => p.Title)
                    .ToPagedList(currentPage, PageSize.pagePosts);

                return View(postModel);
            }

            var Posts = context.Posts.Include(p => p.Tags)
                .Include(p => p.Comments)
                .OrderByDescending(p => p.Time).ToList();

            ViewBag.IsAdmin = IsAdmin;
            postModel.IsAdmin = IsAdmin;
            postModel.PageNumber = currentPage;

            postModel.Posts = Posts.ToPagedList(currentPage, PageSize.pagePosts);
            return View(postModel);
        }

        //public ActionResult RSS()
        //{
        //    IEnumerable<SyndicationItem> posts = context.Posts
        //        .Where(p => p.Time < DateTime.Now)
        //        .OrderByDescending(p => p.Time)
        //        .Take(postsPerFeed)
        //        .ToList()
        //        .Select(p => GetSyndicationItem(p));

        //    //response is the feed of items
        //    SyndicationFeed feed = new SyndicationFeed("Dev", "Dev Community", new Uri("https://dev.to/"), posts);
        //    Rss20FeedFormatter formattedFeed = new Rss20FeedFormatter(feed);

        //    return new FeedResult(formattedFeed);
        //}

        private SyndicationItem GetSyndicationItem(Post post)
        {
            return new SyndicationItem(post.Title, post.Body, new Uri("http://localhost:65008/Posts/Details/" + post.Id));
        }

        public ActionResult Details(int id , int? page)
        {
            int currentPage = page ?? 1;

            var post = GetPost(id);
            postModel.Post = post;

            if(post.PinCommentId.HasValue)
            {
                postModel.Comments = post.Comments.OrderByDescending(c => c.Id == post.PinCommentId.Value).ThenByDescending(c => c.Time).ToPagedList(currentPage, PageSize.pageComments);
            }
            else
            {
                postModel.Comments = post.Comments.OrderByDescending(c => c.Time).ToPagedList(currentPage, PageSize.pageComments);
            }

            ViewBag.IsAdmin = IsAdmin;

            return View(postModel);
        }

        //get view of add & edit
        public ActionResult Edit(int? id)
        {
            Post post = GetPost(id);
            StringBuilder tagList = new StringBuilder();
            foreach (var tag in post.Tags)
            {
                tagList.AppendFormat("{0} ", tag.Name);
            }
            ViewBag.Tags = tagList.ToString();
            ViewBag.IsAdmin = IsAdmin;

            return View(post);
        }

        //post add & edit
        [ValidateInput(false)]
        public ActionResult Update(AddPostViewModel postModel, string tags)
        {
            Post post = GetPost(postModel.Id);

            if (!IsAdmin)
            {
                return RedirectToAction("Index");
            }

            if(!ModelState.IsValid)
            {
                Post emptyPost = new Post();
                return View("edit", emptyPost);
            }

            if (postModel.PostImageFile != null)
            {
                //upload a pic
                string fileName = Path.GetFileNameWithoutExtension(postModel.PostImageFile.FileName);
                string extension = Path.GetExtension(postModel.PostImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;

                postModel.PostImageUrl = "~/Images/Upload_Images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Images/Upload_Images"), fileName);
                postModel.PostImageFile.SaveAs(fileName);

                post.PostImageUrl = postModel.PostImageUrl;
                Session["PostImage"] = postModel.PostImageFile;
            }

            //edit
            post.Title = postModel.Title;
            post.EditTime = DateTime.Now;
            post.Body = postModel.Body;
            post.Tags.Clear();

            //to avoid null referenece exception
            tags = tags ?? string.Empty;

            //stringSplitOption : for removing empty array from splitting
            var tagNames = tags.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var tagName in tagNames)
            {
                post.Tags.Add(GetTagFromDb(tagName));
            }

            //Create
            if (postModel.Id == 0)
            {
                post.EditTime = null;
                post.Time = DateTime.Now;
                context.Posts.Add(post);
            }
            context.SaveChanges();

            return RedirectToAction("Details", new { id = post.Id });
        }

        public ActionResult Delete(int id , int? page)
        {
            int currentPage = page != 0 ? page.Value : 1;
            if (IsAdmin)
            {
                var post = GetPost(id);
                context.Posts.Remove(post);
                context.SaveChanges();
            }
            return RedirectToAction("Index", new { page = currentPage});
        }

        [HttpPost]
        public JsonResult DeleteComment(int id)
        {
            var comment = context.Comments.Where(c => c.Id == id).First();

            bool result = false;
            if (IsAdmin)
            {
                context.Comments.Remove(comment);
                result = context.SaveChanges() > 0;
            }

            if (result)
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);

            return Json(new { success = false, message = "OPPS! Something went wrong." }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Comment(int id, Comment commentForm)
        {
            JsonResult json = new JsonResult();

            if(!ModelState.IsValid)
            {
                var errors = ModelState.Values.Select(v => v.Errors).ToList();

                var nameError = errors[1].Select(e => e.ErrorMessage).FirstOrDefault();
                var emailError = errors[2].Select(e => e.ErrorMessage).FirstOrDefault();
                var commentError = errors[3].Select(e => e.ErrorMessage).FirstOrDefault();

                return Json(new { modelNotValid = true , nameError = nameError , emailError = emailError , commentError = commentError });
            }

            var post = GetPost(id);
            var comment = new Comment();

            comment.Name = commentForm.Name;
            comment.Email = commentForm.Email;
            comment.Body = commentForm.Body;
            comment.Post = post;
            comment.Time = DateTime.Now;
            comment.IsAdmin = commentForm.IsAdmin;

            context.Comments.Add(comment);
            bool result = context.SaveChanges() > 0;

            if (result)
            {
                return Json(new { success = true } , JsonRequestBehavior.AllowGet);
            }
            else
               return Json(new { success = false, message = "OOPS! Something went wrong." } , JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public JsonResult GetComments(int id)
        {
            var comments = context.Posts.Where(p => p.Id == id).Select(p => p.Comments).ToList();

            return Json(new { comments = comments }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult PinComment(int id, int commentId)
        {
            var post = GetPost(id);
            post.PinCommentId = commentId;

            context.Entry(post).State = EntityState.Modified;
            bool result = context.SaveChanges() > 0;

            if (result)
                return Json(new { success = true });

            return Json(new { success = false , message = "OPPS! Something went wrong."});
        }

        [HttpPost]
        public ActionResult UnPinComment(int id)
        {
            var post = GetPost(id);
            post.PinCommentId = null;

            context.Entry(post).State = EntityState.Modified;
            bool result = context.SaveChanges() > 0;

             if (result)
                return Json(new { success = true });

             return Json(new { success = false, message = "OPPS! Something went wrong." });
        }

        public ActionResult Tags(string tagName, int? page)
        {
            postModel.Posts = GetTagPostsByTagName(tagName, page);
            postModel.TagName = tagName;
            return View("Index", postModel);
        }

        [ChildActionOnly]
        public PartialViewResult TrendingTags()
        {
            postModel.Tags = context.Tags.Where(t => t.Posts.Count() >= TotalTrendingTags.TrendingTagsNumber).Include(t => t.Posts).ToList();
            postModel.IsAdmin = IsAdmin;
            ViewBag.adminPic = AdminPicUrl();

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/images/logo.png")" style="width:20px;" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("ExtraHeaders", required: false)
    @Scripts.Render("~/bundles/jquery")

</head>
<body id="body">

    @Html.Action("TrendingTags", "Posts")

    <img src="~/Images/weather.png" id="toggleMenu" onclick="toggleMenu()" style="width:60px;" alt="weather">

    <nav id="menu">
        <img class="weatherIcon"/>
        <p class="description"></p>
        <p class="cityName"></p>
        <p class="temp"></p>
    </nav>
   

    <div id="content">
        <div id="main">
            @RenderBody()
        </div>
    </div>

    <div id="footer">
        <div id="copyright">Copyright &copy; @DateTime.Now.Year, <label style="font-family: 'Space Age'">Sully</label> </div>
    </div>

    <script src="~/Scripts/jquery-ui-1.8.24.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    @RenderSection("scripts", required: false)
</body>

</html>

<script>
    $(document).ready(function () {
        $(".navbar").dblclick(function () {
            $("#loginLink").toggle();
            debugger;
        })

        $(function () {
            $("#postSearch").autocomplete({
                source: '@Url.Action("GetCompeletedSearch")',
            });
        });
    });

    var toggleStatus = 0;
    function toggleMenu() {
        if (toggleStatus == 1) {
            document.getElementById("menu").style.left = "-200px";
            document.getElementById("toggleMenu").style.left = "3px";
            toggleStatus = 0;
        } else if (toggleStatus == 0) {
            document.getElementById("menu").style.left = "3px";
            document.getElementById("toggleMenu").style.left = "200px";
            toggleStatus = 1;
        }
    }
</script>

<script>
   
    if ("geolocation" in navigator) { //check geolocation available 
           //try to get user current location using getCurrentPosition() method
        navigator.geolocation.getCurrentPosition(function (position) {
            var lat = position.coords.latitude ;
            var lon = position.coords.longitude;

            debugger;
            var url = "http://api.openweathermap.org/data/2.5/weather?lat=" + lat + "&lon=" + lon + "&units=metric&APPID=768644037f130039fae040567559985f";

            $.getJSON(url,function(data){
                var icon = "http://openweathermap.org/img/w/" + data.weather[0].icon + ".png";
                var city = data.name;
                var temp = data.main.temp;
                var desc = data.weather[0].description;

                $(".weatherIcon").attr("src", icon);
                $(".weatherMain").append(desc);
                $(".cityName").append(city);
                $(".temp").append(temp + " °C");
                $(".description").append(desc);
            });
        })
     } else {
        console.log("Browser doesn't support geolocation!");
    }
</script>

Blog/Views/Shared/_NavBar.cshtml
@model Blog.ViewModel.PostViewModel

<div class="navbar">
    <a href="@Href("~/")">
        <img src="@Href("~/images/logo.png")" alt="Logo" style="width:20px;" />
        <img src="@Href("~/images/title.png")" alt="Sully" style="width:100px;">
    </a>
    <a href="@Href("~/Posts/Index/#body")">
        <i class="fa fa-home" aria-hidden="true"></i> Home
    </a>
    <div class="dropdown">
        <button class="dropbtn">
            <i class="fa fa-external-link-square" aria-hidden="true"></i>
            Trending Tags
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @if (Model.Tags != null && Model.Tags.Count() > 0)
            {
                foreach (var tag in Model.Tags.OrderByDescending(t => t.Posts.Count()))
                {
                    <a href="@Href("~/Posts/Tags?tagName=" + tag.Name)" style="color:darkgoldenrod">#@tag.Name (@tag.Posts.Count())</a>
                }
            }
        </div>
    </div>

    <a href="@Href("~/accounts/aboutadmin")">
        <img src="@Url.Content(ViewBag.adminPic)" class="img" align="top"> Profile
    </a>

    @if (Model.IsAdmin)
    {
        <a style="float:right" href="@Href("~/Accounts/Logout")"> <i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
        <a style="float:right" href="@Href("~/Posts/Edit")"><i class="fa fa-plus-square" aria-hidden="true"></i> New Post</a>
    }
    else
    {
        <a id="loginLink" style="float:right; display:none;" href="@Href("~/accounts/Login")"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
    }
    <div class="search-container">
        <form action="@Href("~/Posts/Index")">
            <input type="text" name="postSearch" id="postSearch" placeholder="Search..." />
            <button type="button" ><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>